### ISSUE TITLE
undeclared identifier: 'GetJsonRpcRequestHeaders'

### ISSUE THREAD

**Issue by gogolxdong** [status-im/nim-web3#48]
undeclared identifier: 'GetJsonRpcRequestHeaders' on master
```
Nim Compiler Version 1.6.4 [Windows: amd64]
Compiled at 2022-02-27
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 7994556f3804c217035c44b453a3feec64405758
active boot switches: -d:release
```

**Comment by tavurth** [comment]
As I understand this is because `GetJsonRpcRequestHeaders` is stored here:

https://github.com/status-im/nim-json-rpc/blob/c8cbe08de756d65e7d085c409dfcb5edfba4aa5d/json_rpc/client.nim#L22

The way I've found to work through this issue is to clone the `nimbus-eth2` repository (https://github.com/status-im/nimbus-eth2)

Then enter the repository and run `source nimbus-eth2/env.sh`

Could you try that?
